### ISSUE TITLE
Conflict with Laravel Twig Bridge package

### ISSUE THREAD

**Issue by garyblankenship** [harryxu/laravel-theme#2]
This seems to have a conflict with the Laravel-TwigBridge package.
_corrected_ https://github.com/rcrowe/TwigBridge

**Comment by harryxu** [comment]
I have not used Laravel-TwigBridge, more details?

**Comment by garyblankenship** [comment]
Reinstalled it to find the errors again.  When it finds a home.twig file in the path, the error is:
_Twig_Error_Loader_
The "/home/user/public/themes/mytheme/views/redbean-laravel4" directory does not exist.
on line 93 in …/­vendor/­twig/­twig/­lib/­Twig/­Loader/­Filesystem.php

The mention of 'redbean-laravel4' is another package/provider that is installed and not part of the views at all.  Not sure why it would use that as a path to look in. However, it could be that this package is the actual conflict.
https://github.com/valedaemon/redbean-laravel4

Removing redbean-laravel4 package allows TwigBridge to work with Laravel Theme so far, and supports both Twig and Blade.  Removing Laravel Theme, allows TwigBridge and Redbean-Laravel4 packages to work together fine, so it could be that the three of them together have some unresolved conflict.
